services:
- docker
language: python
matrix:
  include:
  - python: '3.6'
before_install:
- pip install pip --upgrade
install:
- pip install yamllint
script:
- yamllint pb_nautobot_install.yml
- docker run --rm -i hadolint/hadolint < Dockerfile
- docker build -t networktocode/nautobot-lab:latest .
- docker run -itd --name nautobot networktocode/nautobot-lab:latest
- sleep 30
- docker exec -it nautobot load-mock-data
- docker exec -it nautobot pytest ./templates/tests/tests.py
deploy:
- provider: script
  script: bash ./deploy/docker.sh
  on:
    branch: main
- provider: script
  script: bash ./deploy/docker.sh
  on:
    tags: true
